create table if not exists raw.raw_bts_flights (
    year integer,
    quarter integer,
    month integer,
    day_of_month integer,
    flight_date date,
    reporting_airline text,
    tail_number text,
    flight_number_reporting_airline text,
    origin text,
    origin_city_name text,
    origin_state_abr text,
    dest text,
    dest_city_name text,
    dest_state_abr text,
    crs_dep_time integer,
    dep_time integer,
    dep_delay numeric,
    dep_delay_minutes numeric,
    taxi_out numeric,
    wheels_off integer,
    wheels_on integer,
    taxi_in numeric,
    crs_arr_time integer,
    arr_time integer,
    arr_delay numeric,
    arr_delay_minutes numeric,
    cancelled numeric,
    cancellation_code text,
    diverted numeric,
    crs_elapsed_time numeric,
    actual_elapsed_time numeric,
    air_time numeric,
    flights numeric,
    distance numeric,
    carrier_delay numeric,
    weather_delay numeric,
    nas_delay numeric,
    security_delay numeric,
    late_aircraft_delay numeric,
    source_file text,
    loaded_at timestamp default current_timestamp
);

create table if not exists raw.raw_airports (
    id bigint,
    ident text,
    type text,
    name text,
    latitude_deg numeric,
    longitude_deg numeric,
    elevation_ft numeric,
    continent text,
    iso_country text,
    iso_region text,
    municipality text,
    scheduled_service text,
    gps_code text,
    iata_code text,
    local_code text,
    home_link text,
    wikipedia_link text,
    keywords text,
    source_file text,
    loaded_at timestamp default current_timestamp
);

create table if not exists raw.raw_countries (
    id bigint,
    code text,
    name text,
    continent text,
    wikipedia_link text,
    keywords text,
    source_file text,
    loaded_at timestamp default current_timestamp
);

create table if not exists raw.raw_regions (
    id bigint,
    code text,
    local_code text,
    name text,
    continent text,
    iso_country text,
    wikipedia_link text,
    keywords text,
    source_file text,
    loaded_at timestamp default current_timestamp
);

create table if not exists raw.raw_bookings (
    booking_id text,
    customer_id text,
    flight_id text,
    flight_date date,
    airline text,
    origin_airport text,
    destination_airport text,
    route text,
    booking_time timestamp,
    booking_channel text,
    customer_segment text,
    ticket_price numeric,
    currency text,
    booking_status text,
    payment_status text,
    is_refunded boolean,
    created_at timestamp,
    updated_at timestamp,
    source_file text,
    loaded_at timestamp default current_timestamp
);

create table if not exists raw.raw_payments (
    payment_id text,
    booking_id text,
    payment_time timestamp,
    payment_method text,
    payment_status text,
    amount numeric,
    currency text,
    refund_amount numeric,
    created_at timestamp,
    updated_at timestamp,
    source_file text,
    loaded_at timestamp default current_timestamp
);
